# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kj4WsAIZd33w0PgcfdhyBKhtZeGKmru9
"""

var = int(input("Enter Number to get the table "))
count = 1

while(count <=10):
  var1 = var * count
  print(var, "x" ,count, "=", var1)
  count += 1